//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeBind.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWindowTopMost {
            get {
                return ((bool)(this["MainWindowTopMost"]));
            }
            set {
                this["MainWindowTopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InputSimulationPaused {
            get {
                return ((bool)(this["InputSimulationPaused"]));
            }
            set {
                this["InputSimulationPaused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActivationSoundEnabled {
            get {
                return ((bool)(this["ActivationSoundEnabled"]));
            }
            set {
                this["ActivationSoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeactivationSoundEnabled {
            get {
                return ((bool)(this["DeactivationSoundEnabled"]));
            }
            set {
                this["DeactivationSoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeftEyeBlinkEnabled {
            get {
                return ((bool)(this["LeftEyeBlinkEnabled"]));
            }
            set {
                this["LeftEyeBlinkEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RightEyeBlinkEnabled {
            get {
                return ((bool)(this["RightEyeBlinkEnabled"]));
            }
            set {
                this["RightEyeBlinkEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EyeBlinkEnabled {
            get {
                return ((bool)(this["EyeBlinkEnabled"]));
            }
            set {
                this["EyeBlinkEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlinkActivationSoundEnabled {
            get {
                return ((bool)(this["BlinkActivationSoundEnabled"]));
            }
            set {
                this["BlinkActivationSoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LastUsedProfileIndex {
            get {
                return ((int)(this["LastUsedProfileIndex"]));
            }
            set {
                this["LastUsedProfileIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys MouseMoveHotKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["MouseMoveHotKey"]));
            }
            set {
                this["MouseMoveHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys ToggleKeyboardSimulationHotKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleKeyboardSimulationHotKey"]));
            }
            set {
                this["ToggleKeyboardSimulationHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys ToggleSoundsHotKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleSoundsHotKey"]));
            }
            set {
                this["ToggleSoundsHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys ToggleContinuousMouseMoveHotKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleContinuousMouseMoveHotKey"]));
            }
            set {
                this["ToggleContinuousMouseMoveHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys ToggleGazeMarkerHotKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleGazeMarkerHotKey"]));
            }
            set {
                this["ToggleGazeMarkerHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlobalSoundEnabled {
            get {
                return ((bool)(this["GlobalSoundEnabled"]));
            }
            set {
                this["GlobalSoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GazeEnterSoundEnabled {
            get {
                return ((bool)(this["GazeEnterSoundEnabled"]));
            }
            set {
                this["GazeEnterSoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GazeExitSoundEnabled {
            get {
                return ((bool)(this["GazeExitSoundEnabled"]));
            }
            set {
                this["GazeExitSoundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FirstPersonShooter")]
        public global::EyeBind.MouseMoveMode MouseMoveMode {
            get {
                return ((global::EyeBind.MouseMoveMode)(this["MouseMoveMode"]));
            }
            set {
                this["MouseMoveMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MouseMoveFollowSpeed {
            get {
                return ((int)(this["MouseMoveFollowSpeed"]));
            }
            set {
                this["MouseMoveFollowSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MouseMoveFirstPersonSpeed {
            get {
                return ((int)(this["MouseMoveFirstPersonSpeed"]));
            }
            set {
                this["MouseMoveFirstPersonSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MouseMoveFirstPersonSpeedMultiplier {
            get {
                return ((int)(this["MouseMoveFirstPersonSpeedMultiplier"]));
            }
            set {
                this["MouseMoveFirstPersonSpeedMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MouseMoveStopDistance {
            get {
                return ((int)(this["MouseMoveStopDistance"]));
            }
            set {
                this["MouseMoveStopDistance"] = value;
            }
        }
    }
}
